const NANO = {
  BUTTON: 'button',
  TEXT: 'text',
  ACTIVITYINDICATOR: 'activityindicator',
  ICON: 'avataricon',
  IMAGE: 'avatarimage',
  TEXTAVATAR: 'avatartext',
  BADGE: 'badge',
  CHECKBOX: 'checkbox',
  CHIP: 'chip',
  FAB: 'fab',
  PROGRESSBAR: 'progressbar',
  RADIOBUTTON: 'radiobutton',
  SWITCH: 'switch',
  TEXTINPUT: 'textinput',
  BANNER: 'banner',
  CARD: 'card',
  DIVIDER: 'divider',
  LISTVIEW: 'listview',
  CUSTOM: 'custom',
  VIEW: 'view',
};
export default NANO;
