const NANO = {
  BUTTON: 'button',
  TEXT: 'text',
  ACTIVITY_INDICATOR: 'activity_indicator',
  AVATAR_ICON: 'avatar_icon',
  CUSTOM_ICON: 'custom_icon',
  AVATAR_IMAGE: 'avatar_image',
  AVATAR_TEXT: 'avatar_text',
  BADGE: 'badge',
  CHECKBOX: 'checkbox',
  CHIP: 'chip',
  FAB: 'fab',
  PROGRESS_BAR: 'progress_bar',
  RADIO_BUTTON: 'radio_button',
  SWITCH: 'switch',
  ICON_BUTTON: 'icon_button',
  TEXT_INPUT: 'text_input',
  BANNER: 'banner',
  CARD: 'card',
  SEARCH_BAR: 'search_bar',
  SEGMENTED_BUTTONS: 'segmented_buttons',
  SNACKBAR: 'snackbar',
  TOOLTIP: 'tooltip',
  IMAGE: 'image',
  MENU: 'menu',
  DIVIDER: 'divider',
  LIST_VIEW: 'list_view',
  VIEW: 'view',
  FLAT_LIST: 'flat_list',
  BOTTOM_TABS: 'bottom_tabs',
  DRAWER: 'drawer',
  TOP_TABS: 'top_tabs',
  BOTTOM_BAR: 'bottom_bar',
  TOP_BAR: 'top_bar',
};
export default NANO;
