interface NANOTYPE {
  BUTTON: string;
  TEXT: string;
  ACTIVITY_INDICATOR: string;
  AVATAR_ICON: string;
  CUSTOM_ICON: string;
  AVATAR_IMAGE: string;
  AVATAR_TEXT: string;
  BADGE: string;
  CHECKBOX: string;
  CHIP: string;
  FAB: string;
  PROGRESS_BAR: string;
  RADIO_BUTTON: string;
  SWITCH: string;
  ICON_BUTTON: string;
  TEXT_INPUT: string;
  BANNER: string;
  CARD: string;
  CARD_TITLE: string;
  CARD_CONTENT: string;
  CARD_ACTION: string;
  CARD_COVER: string;
  DIALOG: string;
  DIALOG_TITLE: string;
  DIALOG_CONTENT: string;
  DIALOG_ACTION: string;
  DIALOG_SCROLLAREA: string;
  SEARCH_BAR: string;
  SEGMENTED_BUTTONS: string;
  SNACKBAR: string;
  TOOLTIP: string;
  IMAGE: string;
  MENU: string;
  DIVIDER: string;
  LIST_VIEW: string;
  VIEW: string;
  FLAT_LIST: string;
  BOTTOM_TABS: string;
  DRAWER: string;
  TOP_TABS: string;
  BOTTOM_BAR: string;
  TOP_BAR: string;
  YOUTUBE_PLAYER: string;
  MODAL: string;
  VIDEO: string;
  SCROLL_VIEW: string;
  HELPER_TEXT: string;
  APPBAR_ACTION: string;
  APPBAR_BACK_ACTION: string;
  APPBAR_CONTENT: string;
  APPBAR_HEADER: string;
  ANIMATED_VIEW: string;
  REANIMATED_COMPONENT: string;
}

const NANO: NANOTYPE = {
  BUTTON: 'button',
  TEXT: 'text',
  ACTIVITY_INDICATOR: 'activity_indicator',
  AVATAR_ICON: 'avatar_icon',
  CUSTOM_ICON: 'custom_icon',
  AVATAR_IMAGE: 'avatar_image',
  AVATAR_TEXT: 'avatar_text',
  BADGE: 'badge',
  CHECKBOX: 'checkbox',
  CHIP: 'chip',
  FAB: 'fab',
  PROGRESS_BAR: 'progress_bar',
  RADIO_BUTTON: 'radio_button',
  SWITCH: 'switch',
  ICON_BUTTON: 'icon_button',
  TEXT_INPUT: 'text_input',
  BANNER: 'banner',
  CARD: 'card',
  CARD_TITLE: 'card_title',
  CARD_CONTENT: 'card_content',
  CARD_ACTION: 'card_action',
  CARD_COVER: 'card_cover',

  DIALOG: 'dialog',
  DIALOG_TITLE: 'dialog_title',
  DIALOG_CONTENT: 'dialog_content',
  DIALOG_ACTION: 'dialog_action',
  DIALOG_SCROLLAREA: 'dialog_scrollarea',

  SEARCH_BAR: 'search_bar',
  SEGMENTED_BUTTONS: 'segmented_buttons',
  SNACKBAR: 'snackbar',
  TOOLTIP: 'tooltip',
  IMAGE: 'image',
  MENU: 'menu',
  DIVIDER: 'divider',
  LIST_VIEW: 'list_view',
  VIEW: 'view',
  FLAT_LIST: 'flat_list',
  BOTTOM_TABS: 'bottom_tabs',
  DRAWER: 'drawer',
  TOP_TABS: 'top_tabs',
  BOTTOM_BAR: 'bottom_bar',
  TOP_BAR: 'top_bar',
  YOUTUBE_PLAYER: 'youtube_player',
  MODAL: 'modal',
  VIDEO: 'video',
  SCROLL_VIEW: 'scroll_view',
  HELPER_TEXT: 'helper_text',
  APPBAR_ACTION: 'appbar_action',
  APPBAR_BACK_ACTION: 'appbar_back_action',
  APPBAR_CONTENT: 'appbar_content',
  APPBAR_HEADER: 'appbar_header',
  ANIMATED_VIEW: 'animated_view',

  REANIMATED_COMPONENT: 'reanimated_component',
};
export default NANO;
